name: "Update locales sources"

on:
  push:
    branches:
      - "master"

jobs:
  push-on-transifex:
    name: "Push locales sources"
    uses: "glpi-project/plugin-translation-workflows/.github/workflows/transifex-push-sources.yml@v1"
    secrets:
      transifex-token: "${{ secrets.TSMR_TRANSIFEX_TOKEN }}"
